name: Build Project
on:
  push:
env:
  project: godot-keylogger
  
jobs:
  build:
    name: Builds extensions for ${{ matrix.platform }}
    runs-on: ${{ matrix.runner }}
    defaults:
      run:
        # Use bash shells on all platforms.
        shell: bash
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux
            target: x86_64-unknown-linux-gnu
            output: libgodot_keylogger
            ext: so
    steps:
      - uses: actions/checkout@v4
      - name: Setup Rust
        uses: actions-rust-lang/setup-rust-toolchain@v1.11.0
      - name: Fetch Linux dependencies
        if: matrix.platform == 'linux'
        run: |
          sudo apt update
          sudo apt install -y libudev-dev libinput-dev
      - name: Build extension
        run: |
          make package
          cp LICENSE.md README.md "addons/keylogger"
      - name: Save artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.project }}.${{ matrix.platform }}
          path: addons/*
